import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import {Toaster} from "@/components/ui/sonner";
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
    return (
        <ClerkProvider>
            <html lang="tr">
            <body className={inter.className}>
            <Toaster/>
            {children}
            </body>
            </html>
        </ClerkProvider>
    );
}
